// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCohgESUpUz1pgDVg-WvN72HSc2kmQZ4E4',
    appId: '1:410986217788:web:1c5c014495dd0ed8119e39',
    messagingSenderId: '410986217788',
    projectId: 'rally-tester-01',
    authDomain: 'rally-tester-01.firebaseapp.com',
    databaseURL: 'https://rally-tester-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rally-tester-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkTYlKvAw9-_yvWWTh75_1WbslgkR2Lcg',
    appId: '1:410986217788:android:429c6cda36c4b65d119e39',
    messagingSenderId: '410986217788',
    projectId: 'rally-tester-01',
    databaseURL: 'https://rally-tester-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rally-tester-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZO5yzFZEAu11ozYV3LAW-iULPq_4Q81E',
    appId: '1:410986217788:ios:fc425dfc604b91b7119e39',
    messagingSenderId: '410986217788',
    projectId: 'rally-tester-01',
    databaseURL: 'https://rally-tester-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rally-tester-01.firebasestorage.app',
    iosBundleId: 'com.example.rallyNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZO5yzFZEAu11ozYV3LAW-iULPq_4Q81E',
    appId: '1:410986217788:ios:fc425dfc604b91b7119e39',
    messagingSenderId: '410986217788',
    projectId: 'rally-tester-01',
    databaseURL: 'https://rally-tester-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rally-tester-01.firebasestorage.app',
    iosBundleId: 'com.example.rallyNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCohgESUpUz1pgDVg-WvN72HSc2kmQZ4E4',
    appId: '1:410986217788:web:cd9814dbcd6ae358119e39',
    messagingSenderId: '410986217788',
    projectId: 'rally-tester-01',
    authDomain: 'rally-tester-01.firebaseapp.com',
    databaseURL: 'https://rally-tester-01-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'rally-tester-01.firebasestorage.app',
  );
}
